annotations: {}
labels: {}

argoProject:
  enabled: enable
  namespace: argocd
  annotations: {}
  labels: {}
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - name: '*'
      namespace: '*'
      server: '*'
    sourceRepos:
    - '*'
