{{- range $name, $tenant := .Values.namespaces }}
{{- range $tenant.resourceQuotas }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}
  namespace: {{ $name }}
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if .annotations }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}