{{- range $name, $tenant := .Values.namespaces }}
{{- range $tenant.limitRanges }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}
  namespace: {{ $name }}
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if .annotations }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  limits:
  {{- toYaml .limits | nindent 4}}
{{- end }}
{{- end }}