apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  sourceRepos:
  - '*' # For workshop and demos set this to '*', for production close it down to specific git repositories
  # Only permit applications to deploy to these namespace in specific clusters
  destinations:
  - namespace: assets
    name: spoke-prod
  - namespace: carts
    name: spoke-prod
  - namespace: catalog
    name: spoke-prod
  - namespace: checkout
    name: spoke-prod
  - namespace: orders
    name: spoke-prod
  - namespace: rabbitmq
    name: spoke-prod
  - namespace: ui
    name: spoke-prod
  - namespace: assets
    name: spoke-staging
  - namespace: carts
    name: spoke-staging
  - namespace: catalog
    name: spoke-staging
  - namespace: checkout
    name: spoke-staging
  - namespace: orders
    name: spoke-staging
  - namespace: rabbitmq
    name: spoke-staging
  - namespace: ui
    name: spoke-staging
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  # Deny all namespaced-scoped resources from being created, except for these
  namespaceResourceWhitelist:
  - group: ''
    kind: Pod
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'apps'
    kind: ReplicaSet
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'dynamodb.services.k8s.aws'
    kind: Table
