name: frontend
labels:
  environment: prod

namespaces:
  assets:
    labels:
      additionalLabels:
        app.kubernetes.io/created-by: eks-workshop
  ui:
    labels:
      additionalLabels:
        app.kubernetes.io/created-by: eks-workshop
