{{- range $name, $tenant := .Values.namespaces }}
{{- range $tenant.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  namespace: {{ $name }}
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if .annotations }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
subjects:
  {{- toYaml .subjects | nindent 2 }}
roleRef:
  {{- toYaml .roleRef | nindent 2 }}
{{- end }}
{{- end }}
