{{- range $name, $tenant := .Values.namespaces }}
{{- range $tenant.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  namespace: {{ $name }}
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if .annotations }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}
{{- end }}
