{{- range $name, $tenant := .Values.namespaces }}
{{- with $tenant }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if and .annotations .annotations.additionalAnnotations }}
    {{- with .annotations.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if and .annotations .annotations.scheduler }}
    {{- with .annotations.scheduler }}
    {{- if .defaultTolerations }}
    scheduler.alpha.kubernetes.io/defaultTolerations: {{ toJson .defaultTolerations | quote }}
    {{- end }}
    {{- end }}
    {{- if .nodeSelector }}
    scheduler.alpha.kubernetes.io/node-selector: {{ .nodeSelector | quote }}
    {{- end }}
    {{- if .tolerationsWhitelist }}
    scheduler.alpha.kubernetes.io/tolerationsWhitelist: {{ toJson .tolerationsWhitelist | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if and .labels .labels.additionalLabels }}
    {{- with .labels.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if and .labels .labels.podSecurityAdmission }}
    {{- with .labels.podSecurityAdmission }}
    {{- if and .audit .audit.standard }}
    pod-security.kubernetes.io/audit: {{ toJson .audit.standard }}
    {{- end }}
    {{- if and .audit .audit.version }}
    pod-security.kubernetes.io/audit-version: {{ toJson .audit.version }}
    {{- end }}
    {{- if and .enforce .enforce.standard }}
    pod-security.kubernetes.io/enforce: {{ toJson .enforce.standard }}
    {{- end }}
    {{- if and .enforce .enforce.version }}
    pod-security.kubernetes.io/enforce-version: {{ toJson .enforce.version }}
    {{- end }}
    {{- if and .audit .warn.standard }}
    pod-security.kubernetes.io/warn: {{ toJson .warn.standard }}
    {{- end }}
    {{- if and .audit .warn.version }}
    pod-security.kubernetes.io/warn-version: {{ toJson .warn.version }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}

