apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
#- try-namespace.yaml # namespaces are not allowed to be created by apps team in project workloads

configMapGenerator:
- name: carts
  behavior: merge
  literals:
  - CARTS_DYNAMODB_TABLENAME=Items-Staging

patches:
  - patch: |-
      apiVersion: dynamodb.services.k8s.aws/v1alpha1
      kind: Table
      metadata:
        name: items-staging
      spec:
        tableName: Items-Staging
    options:
      allowNameChange: true
    target:
      group: dynamodb.services.k8s.aws
      version: v1alpha1
      kind: Table
      Name: items
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: carts
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/carts-staging-role
    target:
      version: v1
      kind: ServiceAccount
      Name: carts